name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: naveensrinivasan/nonharmful-and-must-have-actions@clean
        with:
         my-secret: ${{ secrets.MY_SECRET_PASSWORD }}
